// Existing and independent language fixtures, with exact Python preview results.
export const previewCases = [
  [
    "Python named Unicode escape in a bundled parser",
    "named.py",
    '@deco("\\N{SNOWMAN}")\ndef visible(): pass\n',
    "@deco('☃') function visible()",
  ],
  [
    "enterprise_language_previews_list_declarations:controller.js",
    "controller.js",
    "if (enabled) {\n  function conditionalOnly() {}\n}\nexport class UserController {\n  async login(request) {\n    function nestedHelper() {}\n    return request;\n  }\n}\nexport const verifyToken = (token) => token;\n",
    "class UserController\nmethod UserController.login\nfunction verifyToken",
  ],
  [
    "enterprise_language_previews_list_declarations:store.ts",
    "store.ts",
    "export interface TokenStore {\n  get(id: string): Token;\n}\nexport function loadStore(): TokenStore { throw new Error(); }\n",
    "interface TokenStore\nmethod TokenStore.get\nfunction loadStore",
  ],
  [
    "enterprise_language_previews_list_declarations:UserService.java",
    "UserService.java",
    'public class UserService {\n  @PostMapping("/login") public User login(String name) { return null; }\n}\n',
    'class UserService\n@PostMapping("/login") method UserService.login',
  ],
  [
    "enterprise_language_previews_list_declarations:UserController.cs",
    "UserController.cs",
    'public class UserController {\n  [HttpPost("login")] public T Login<T>(User user) { return default(T); }\n}\n',
    'class UserController\n[HttpPost("login")] method UserController.Login',
  ],
  [
    "enterprise_language_previews_list_declarations:user_service.rb",
    "user_service.rb",
    "class FirstService\n  def call(user)\n    true\n  end\nend\nclass SecondService\n  def call(user)\n    true\n  end\nend\n",
    "class FirstService\nmethod FirstService.call\nclass SecondService\nmethod SecondService.call",
  ],
  [
    "enterprise_language_previews_list_declarations:UserService.php",
    "UserService.php",
    "<?php\nfinal class UserService {\n  # A comment brace must not change declaration depth: {\n  public function authenticate($user) { return true; }\n}\n",
    "class UserService\nmethod UserService.authenticate",
  ],
  [
    "enterprise_language_previews_list_declarations:user_service.go",
    "user_service.go",
    "package service\ntype UserService struct {}\nfunc (service *UserService) Authenticate(user User) bool { return true }\n",
    "struct UserService\nmethod UserService.Authenticate",
  ],
  [
    "enterprise_language_previews_list_declarations:user_service.cpp",
    "user_service.cpp",
    "Widget widget(options);\nclass UserService {\npublic:\n  bool authenticate(const User& user) { return true; }\n};\nbool verify_token(const Token& token) { return true; }\n",
    "class UserService\nmethod UserService.authenticate\nfunction verify_token",
  ],
  [
    "enterprise_language_previews_list_declarations:UserService.kt",
    "UserService.kt",
    "class UserService {\n  fun authenticate(user: User): Boolean { return true }\n}\n",
    "class UserService\nmethod UserService.authenticate",
  ],
  [
    "enterprise_language_previews_list_declarations:UserService.scala",
    "UserService.scala",
    "class UserService {\n  def authenticate(user: User): Boolean = { true }\n}\n",
    "class UserService\nmethod UserService.authenticate",
  ],
  [
    "enterprise_language_previews_list_declarations:user_service.rs",
    "user_service.rs",
    "pub fn borrow<'a>() {}\nstruct UserService {}\nimpl UserService {\n  pub fn authenticate(&self, user: User) -> bool { true }\n}\n",
    "function borrow\nstruct UserService\nimpl UserService\nmethod UserService.authenticate",
  ],
  [
    "enterprise_language_previews_list_declarations:UserService.swift",
    "UserService.swift",
    "final class UserService {\n  func authenticate(user: User) -> Bool { return true }\n}\n",
    "class UserService\nmethod UserService.authenticate",
  ],
  [
    "enterprise_language_previews_list_declarations:user_service.ex",
    "user_service.ex",
    "defmodule UserService do\n  def authenticate(user), do: true\nend\n",
    "module UserService\nfunction authenticate",
  ],
  [
    "enterprise_language_previews_list_declarations:service.clj",
    "service.clj",
    "(defprotocol UserService\n  (authenticate [service user]))\n(defn verify-token [token] true)\n",
    "defprotocol UserService\ndefn verify-token",
  ],
  [
    "enterprise_language_previews_list_declarations:service.proto",
    "service.proto",
    "service UserService {\n  rpc Authenticate (User) returns (Result);\n}\nmessage User {}\n",
    "service UserService\nrpc Authenticate\nmessage User",
  ],
  [
    "enterprise_language_previews_list_declarations:schema.graphql",
    "schema.graphql",
    'type User { id: ID! }\ntype Query { user(id: ID!): User }\nquery CurrentUser { user(id: "me") { id } }\n',
    "type User\ntype Query\nquery CurrentUser",
  ],
  [
    "enterprise_language_previews_list_declarations:schema.sql",
    "schema.sql",
    "CREATE TABLE users (id BIGINT PRIMARY KEY);\nCREATE PROCEDURE rotate_tokens() BEGIN SELECT 1; END;\n",
    "table users\nprocedure rotate_tokens",
  ],
  [
    "enterprise_language_previews_list_declarations:service.json",
    "service.json",
    '{"service":{"host":"localhost","port":443},"enabled":true}',
    "key service [host, port]\nkey enabled",
  ],
  [
    "expression_bodied_function_does_not_consume_next_type_body",
    "Service.kt",
    "fun answer(): Int = 42\nclass Service {\n  fun run() {}\n}\n",
    "function answer\nclass Service\nmethod Service.run",
  ],
  [
    "protocol_requirement_does_not_consume_following_function",
    "Required.swift",
    "protocol Required {\n  func run()\n}\nfunc visible() {}\n",
    "protocol Required\nmethod Required.run\nfunction visible",
  ],
  [
    "multiline_string_and_commented_annotation_do_not_change_depth",
    "Visible.java",
    'public class Visible {\n  String template = """\n    { notABlock }\n  """;\n  /*\n   * @Route("/not-a-route")\n   */\n  public void run() {}\n}\n',
    "class Visible\nmethod Visible.run",
  ],
  [
    "namespace_like_containers_expose_declarations:api.rs",
    "api.rs",
    "mod api {\n  pub fn handle() {}\n}\n",
    "function handle",
  ],
  [
    "namespace_like_containers_expose_declarations:api.ts",
    "api.ts",
    'declare module "api" {\n  export function handle(): void;\n}\n',
    "function handle",
  ],
  [
    "namespace_like_containers_expose_declarations:api.cpp",
    "api.cpp",
    'extern "C" {\n  void handle() {}\n}\n',
    "function handle",
  ],
  [
    "kotlin_companion_object_lists_factory_method",
    "Service.kt",
    "class Service {\n  companion object {\n    fun create() {}\n  }\n  fun visible() {}\n}\n",
    "class Service\nobject Service.Companion\nmethod Service.Companion.create\nmethod Service.visible",
  ],
  [
    "javascript_regex_literal_does_not_change_declaration_depth",
    "service.ts",
    "class Service {\n  pattern = /\\{/;\n  visible() {}\n}\n",
    "class Service\nmethod Service.visible",
  ],
  [
    "javascript_preview_lists_class_field_arrow_handlers",
    "controller.ts",
    "export class Controller {\n  login = async (request: Request) => request;\n  public refresh: Handler = (request) => request;\n  protected validate = value => Boolean(value);\n}\n",
    "class Controller\nmethod Controller.login\nmethod Controller.refresh\nmethod Controller.validate",
  ],
  [
    "php_heredoc_does_not_hide_following_method",
    "Service.php",
    "<?php\nclass Service {\n  public function template() {\n    $value = <<<TXT\n{\nTXT;\n  }\n  public function visible() {}\n}\n",
    "class Service\nmethod Service.template\nmethod Service.visible",
  ],
  [
    "malformed_python_uses_sampled_source_fallback",
    "broken.py",
    "import package\nbroken = (\nfirst_runtime_line()\nsecond_runtime_line()\n",
    "import package\nbroken = (\nfirst_runtime_line()\nsecond_runtime_line()",
  ],
  [
    "Dart",
    "service.dart",
    "class Service {\n  bool check(User user) { return true; }\n}\n",
    "class Service\nmethod Service.check",
  ],
  [
    "Lua",
    "service.lua",
    "local function Service:check(user)\nend\n",
    "function Service:check",
  ],
  [
    "shell",
    "service.sh",
    "function check() {\n echo ok\n}\n",
    "function check",
  ],
  [
    "Haskell",
    "service.hs",
    "data Service = Service\ncheck :: Service -> Bool\n",
    "data Service\nfunction check",
  ],
  [
    "YAML",
    "service.yaml",
    "service:\n  nested: yes\nport: 80\n",
    "key service\nkey port",
  ],
  ["TOML", "service.toml", "[service.web]\nport = 80\n", "section service.web"],
  ["INI", "service.cfg", "[service]\nport=80\n", "section service"],
  [
    "Rust raw strings and nested comments",
    "service.rs",
    'struct Visible {}\nimpl Visible {\n  /* { /* } */ { */\n  fn text() {\n    let text = br##"{ }"##;\n  }\n  fn visible() {}\n}\n',
    "struct Visible\nimpl Visible\nmethod Visible.text\nmethod Visible.visible",
  ],
  [
    "C sharp verbatim string",
    "service.cs",
    'class Visible {\n string text = @"a ""quoted"" {\n}";\n void visible() {}\n}\n',
    "class Visible\nmethod Visible.visible",
  ],
  [
    "Ruby tabs and duplicate methods",
    "service.rb",
    "class Visible\n\tdef text()\n\t\tdef nested()\n\t\tend\n\tend\n\tdef visible()\n\tend\n\tdef visible()\n\tend\nend\n",
    "class Visible\nmethod Visible.text\nmethod Visible.visible",
  ],
  [
    "annotations retain last two",
    "service.ts",
    '@first\n@second\n@third\nclass Visible {\n @call("a") @other() method() {}\n}\n',
    '@second @third class Visible\n@call("a") @other() method Visible.method',
  ],
] as const;
