import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { root } from "./binding.mjs";

// Resolve the same pinned package used by the typed regex compiler.
const require = createRequire(join(root, "../mcp-app/package.json"));
const prefix = "@unicode/unicode-15.0.0/";
type Pair = readonly [number, number];
function ranges(path: string): Pair[] {
  const values = require(`${prefix}${path}/ranges.js`) as {
    begin: number;
    end: number;
  }[];
  return values.map(({ begin, end }) => [begin, end]);
}
function mappings(path: string): Map<number, number> {
  return new Map(
    require(`${prefix}${path}/code-points.js`) as Map<number, number>,
  );
}
const upper = mappings("Simple_Case_Mapping/Uppercase");
for (const [point, values] of require(
  `${prefix}Special_Casing/Uppercase/code-points.js`,
) as Map<number, number[]>) {
  upper.set(point, values[0]!);
}
const tables: [string, Iterable<Pair>][] = [
  ["LETTERS", ranges("General_Category/Letter")],
  ["NUMBERS", ranges("General_Category/Number")],
  ["DIGITS", ranges("General_Category/Decimal_Number")],
  ["SPACES", ranges("Binary_Property/White_Space")],
  ["LOWERCASE", mappings("Simple_Case_Mapping/Lowercase")],
  ["UPPERCASE", upper],
];
const version = (require(`${prefix}package.json`) as { version: string })
  .version;
const source = [
  `// Generated by generate-unicode.mts from @unicode/unicode-15.0.0 ${version}.`,
  "// Half-open ranges and sorted mappings; see native/README.md for provenance.",
  ...tables.map(([name, values]) => {
    const pairs = [...values].sort(([left], [right]) => left - right);
    return `pub const ${name}: &[(u32, u32)] = &[\n${pairs.map(([left, right]) => `    (${left}, ${right}),`).join("\n")}\n];`;
  }),
  "",
].join("\n");
writeFileSync(join(root, "unicode15/src/tables.rs"), source);
console.log(`Generated SRE Unicode 15 tables from package ${version}.`);
